// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package apps

import (
	"github.com/google/wire"
	"github.com/kumin/go-tpc/services/credit_service/configs"
	"github.com/kumin/go-tpc/services/credit_service/handler"
	"github.com/kumin/go-tpc/services/credit_service/infras"
	"github.com/kumin/go-tpc/services/credit_service/repos/mysql"
	"github.com/kumin/go-tpc/services/credit_service/repos/provider"
	"github.com/kumin/go-tpc/services/credit_service/services"
)

// Injectors from wire.go:

func BuildServer() (*HttpServer, error) {
	serverConfiguration := configs.NewServerConfiguration()
	mysqlConnector := infras.NewMysqlConnector()
	walletMysqlRepo := mysql.NewWalletMysqlRepo(mysqlConnector)
	walletService := services.NewWalletService(walletMysqlRepo)
	walletCtlHandler := handler.NewWalletCtlHandler(walletService)
	httpServer := NewHttpServer(serverConfiguration, walletCtlHandler)
	return httpServer, nil
}

// wire.go:

var SuperGraphSet = wire.NewSet(infras.InfaGraphSet, provider.MysqlGraphSet, services.ServiceGraphSet, handler.HandlerGraphSet, ServerGraphSet)
