// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package apps

import (
	"github.com/google/wire"
	"github.com/kumin/go-tpc/services/customer_service/configs"
	"github.com/kumin/go-tpc/services/customer_service/handler"
	"github.com/kumin/go-tpc/services/customer_service/infras"
	"github.com/kumin/go-tpc/services/customer_service/repos/mysql"
	"github.com/kumin/go-tpc/services/customer_service/repos/provider"
	"github.com/kumin/go-tpc/services/customer_service/services"
)

// Injectors from wire.go:

func BuildServer() (*HttpServer, error) {
	serverConfiguration := configs.NewServerConfiguration()
	mysqlConnector := infras.NewMysqlConnector()
	productMysqlRepo := mysql.NewProductMysqlRepo(mysqlConnector)
	productCtlServices := services.NewProductCtlServices(productMysqlRepo)
	productCtlHandler := handler.NewProductCtlHandler(productCtlServices)
	orderMysqlRepo := mysql.NewOrderMysqlRepo(mysqlConnector)
	orderService := services.NewOrderService(orderMysqlRepo)
	orderCtlHandler := handler.NewOrderCtlHandler(orderService)
	httpServer := NewHttpServer(serverConfiguration, productCtlHandler, orderCtlHandler)
	return httpServer, nil
}

// wire.go:

var SuperGraphSet = wire.NewSet(provider.MysqlGraphSet, services.ServiceGraphSet, handler.HandlerGraphSet, ServerGraphSet)
